name: http_test_client
version: 0.0.1
author: jonah williams <jonahwilliams@google.com>
description: A package for testing http clients on flutter or the Dart vm.
homepage: https://github.com/jonahwilliams/http_test_client

dev_dependencies:
  test: ^1.14.4

environment:
  sdk: '>=2.8.1 <3.0.0'
